### Comparing Large Language Model (RAG)

#### Loading the whole dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
file_path = "/content/drive/My Drive/FYP - UoA RAG CHATBOT/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import json
from sklearn.model_selection import train_test_split
import ast
# Example: Load MAUDE reports (replace with your data source)
alldata = pd.read_excel(file_path + 'alldata - C1.xlsx', sheet_name="Sheet1")
maude_reports = pd.DataFrame({
    'report_id': alldata["MDR_REPORT_KEY"].to_list(),
    'FOI_TEXT': alldata["FOI_TEXT"].to_list(),
    'YEAR': alldata["YEAR"].to_list(),
    'PATIENT_SEX': alldata["PATIENT_SEX"].to_list(),
    'BRAND_NAME': alldata["BRAND_NAME"].to_list(),
    'EVENTS': alldata["EVENTS"].to_list()
})
alldata["EVENTS"] = alldata["EVENTS"].apply(lambda x : ast.literal_eval(x))
alldata.shape

(1226, 6)

### Preparing vector database with pretrained GIST Embedding model

In [ ]:
! pip install faiss-cpu streamlit langchain_chroma

In [ ]:
# Set up the retriever with similarity search
ALLMINI_NAME = "sentence-transformers/all-MiniLM-L6-v2"
GIST_NAME = "avsolatorio/GIST-small-Embedding-v0"
import torch
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(DEVICE)

import os
from langchain_chroma import Chroma
import chromadb
from sentence_transformers import SentenceTransformer
import streamlit as st
CHROMA_PATH = file_path + "chroma"
COLLECTION_PRETRAINED_GISTPATH = "langchain-pretrained-GIST"
from langchain.schema import Document

def creating_chromadb(alldata, embeddings = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2"), collection_path = ""):
    print("Generating the Chroma vector DB....")

    # avsolatorio/GIST-small-Embedding-v0


    embedding_function = MyEmbeddingFunction(embeddings)


    client = chromadb.PersistentClient(path=CHROMA_PATH)

    # client.delete_collection(name=COLLECTION_PRETRAINED_GISTPATH)
    collection = client.create_collection(name=collection_path, embedding_function=embedding_function)

    documents = []
    ### Save all reports
    for i, row in alldata.iterrows():
        content = (
            f"MDR_REPORT_KEY: {row['MDR_REPORT_KEY']}\n"
            f"YEAR: {int(row['YEAR'])}\n"
            f"PATIENT_SEX: {row['PATIENT_SEX']}\n"
            f"BRAND_NAME: {row['BRAND_NAME']}\n"
            f"EVENTS: {str(row["EVENTS"])}\n"
        )

        metadata = {
            "MDR_REPORT_KEY": str(row['MDR_REPORT_KEY']),
            # "YEAR": str(row['YEAR']),
            # "PATIENT_SEX": str(row['PATIENT_SEX']),
        }
        documents.append(Document(page_content=content, metadata=metadata)) #

    ### Trends analysis (for patient sex only)
    trend_df = alldata.groupby(["YEAR", "PATIENT_SEX"]).size().reset_index(name="count")
    for sex in trend_df["PATIENT_SEX"].unique():
        group = trend_df[trend_df["PATIENT_SEX"] == sex]
        trend_summary = "\n".join([
            f"In {row['YEAR']}, there were {row['count']} reports for sex {sex}."
            for _, row in group.iterrows()
        ])

        ### Do not added the comma, else it will be tuples. Not string
        trend_doc = (
            f"MDR_REPORT_KEY: adverse_events_by_year_{sex}_{row['YEAR']}"
            f"PATIENT_SEX: {sex}\n"
            f"Adverse event reports per year:\n{trend_summary}"
            f"YEAR: {int(row['YEAR'])}\n"
            f"BRAND_NAME: None"
        )

        metadata = {
            "MDR_REPORT_KEY": f"adverse_events_by_year_{sex}_{row['YEAR']}", # just a fake one
            # "PATIENT_SEX": sex
        }
        documents.append(Document(page_content=trend_doc, metadata=metadata))


    chroma_documents_content = [doc.page_content for doc in documents]
    chroma_metadatas = [doc.metadata for doc in documents]
    chroma_ids = [str(doc.metadata["MDR_REPORT_KEY"]) for doc in documents]
    collection.upsert(
        documents=chroma_documents_content,
        metadatas=chroma_metadatas,
        ids=chroma_ids
    )

    print("Done...")

    return collection

class MyEmbeddingFunction:
    def __init__(self, embedding_model):
        self.embedding_model = embedding_model

    def __call__(self, input):
        # Chroma may call this if it supports function-style
        return self.embedding_model.encode(input, convert_to_tensor=False).tolist()

    def embed_query(self, input):
        return self.embedding_model.encode(input, convert_to_tensor=False).tolist()

    def embed_documents(self, input):
        return self.embedding_model.encode(input, convert_to_tensor=False).tolist()

# embeddings = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2") # , device=DEVICE
embeddings = SentenceTransformer(GIST_NAME, device=DEVICE)
embedding_function = MyEmbeddingFunction(embeddings)

client = chromadb.PersistentClient(path=CHROMA_PATH)

existing_collections = [c.name for c in client.list_collections()]
if COLLECTION_PRETRAINED_GISTPATH in existing_collections:
    print(f"Collection '{COLLECTION_PRETRAINED_GISTPATH}' already exists. Loading it.")
    collection = client.get_collection(COLLECTION_PRETRAINED_GISTPATH)
else:
    print(f"Collection '{COLLECTION_PRETRAINED_GISTPATH}' not found. Creating new one...")
    # client.delete_collection(COLLECTION_PRETRAINED_GISTPATH)
    creating_chromadb(alldata, embeddings, collection_path = COLLECTION_PRETRAINED_GISTPATH)


vectorstore = Chroma(
    collection_name=COLLECTION_PRETRAINED_GISTPATH,
    embedding_function=embedding_function,
    persist_directory=CHROMA_PATH
)
st.session_state.retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 1}
)
st.success("Done")

# GIST-smallEmbedding-v0
# gte-small
# all-MiniLM-L6-v2
# Qwen/Qwen3-Embedding-4B

cuda

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
alldata.head(20)

retrieved_docs = st.session_state.retriever.get_relevant_documents("What are patient gender for report 13935064?")
for i, doc in enumerate(retrieved_docs):
    print(doc.page_content)

2025-07-28 11:31:12.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
/tmp/ipython-input-6-3936114586.py:3: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  retrieved_docs = st.session_state.retriever.get_relevant_documents("What are patient gender for report 13935064?")

MDR_REPORT_KEY: 13933217
YEAR: 2022
PATIENT_SEX: Male
BRAND_NAME: SYNERGY XD

In [ ]:
retriever = vectorstore.as_retriever(search_type="similarity", search_kwargs={"k": 1})
for question in ["What are patient gender for report 13935064?"]:
      retrieved_docs = retriever.get_relevant_documents(question)
      for i, doc in enumerate(retrieved_docs):
          print(doc.page_content)
          negative_report_key = doc.metadata["MDR_REPORT_KEY"]
          print("negative_report_key", negative_report_key)

MDR_REPORT_KEY: 13933217
YEAR: 2022
PATIENT_SEX: Male
BRAND_NAME: SYNERGY XD

negative_report_key 13933217

In [ ]:
import random

client = chromadb.PersistentClient(path=CHROMA_PATH)
collection = client.get_collection(name=COLLECTION_PRETRAINED_GISTPATH)
documents = collection.get(include=["documents", "metadatas", "embeddings"], limit=None)
documents = str(documents["documents"])

data = []
for idx, row in alldata.iterrows():
    string = row["EVENTS"][0]
    for i in row["EVENTS"][1:]:
        string += f" and {i}"

    content = (
        f"MDR_REPORT_KEY: {row['MDR_REPORT_KEY']}\n"
        f"YEAR: {int(row['YEAR'])}\n"
        f"PATIENT_SEX: {row['PATIENT_SEX']}\n"
        f"BRAND_NAME: {row['BRAND_NAME']}\n"
    )
    metadata = {
        "MDR_REPORT_KEY": str(row['MDR_REPORT_KEY']),
    }
    doc = Document(page_content=content, metadata=metadata)


    questions = [f'What are adverse events for report {row["MDR_REPORT_KEY"]}?',
                 f'What are patient gender for report {row["MDR_REPORT_KEY"]}?',
                 f'Which year does we receive report {row["MDR_REPORT_KEY"]} ?']

    retriever = vectorstore.as_retriever(search_type="similarity", search_kwargs={"k": 1})

    for question in questions:
        retrieved_docs = retriever.get_relevant_documents(question)
        for i, doc in enumerate(retrieved_docs):
            negative_report_key = doc.metadata["MDR_REPORT_KEY"]

            if str(negative_report_key).strip() != str(row['MDR_REPORT_KEY']).strip():
                ### get the negative document
                negative_report = alldata[alldata["MDR_REPORT_KEY"] == str(negative_report_key)]
                if negative_report.empty:
                  negative_report = pd.DataFrame(columns=["MDR_REPORT_KEY", "YEAR", "PATIENT_SEX", "BRAND_NAME"])
                  fake_row = {
                      "MDR_REPORT_KEY": str(random.randint(10000000, 19999999)),
                      "YEAR": str(random.choice(range(2010, 2024))),
                      "PATIENT_SEX": random.choice(["Male", "Female", "Unknown"]),
                      "BRAND_NAME": random.choice(["BRAND_A", "BRAND_B", "BRAND_X", "Unknown"])
                  }
                  negative_report = pd.concat([negative_report, pd.DataFrame([fake_row])], ignore_index=True)

                data.append({
                    'anchor': question,
                    'positive':{
                        "doc_id": str(row['MDR_REPORT_KEY']),
                        "text": (
                            f"MDR_REPORT_KEY: {row['MDR_REPORT_KEY']}\n"
                            f"YEAR: {int(row['YEAR'])}\n"
                            f"PATIENT_SEX: {row['PATIENT_SEX']}\n"
                            f"BRAND_NAME: {row['BRAND_NAME']}\n"
                        ),
                    },
                    'negative': {
                        "doc_id": str(negative_report_key),
                        "text": (
                            f"MDR_REPORT_KEY: {negative_report_key}\n"
                            f"YEAR: {negative_report['YEAR'].values[0]}"
                            f"PATIENT_SEX: {negative_report['PATIENT_SEX'].values[0]}\n"
                            f"BRAND_NAME: {negative_report['BRAND_NAME'].values[0]}\n"
                        ),
                    }
                })


# Split into train, validation, test
train_data, temp_data = train_test_split(data, test_size=0.2, random_state=42)
val_data, test_data = train_test_split(temp_data, test_size=0.5, random_state=42)

with open(file_path + 'maude_dataset/train.json', 'w') as f:
    json.dump(train_data, f)
with open(file_path + 'maude_dataset/val.json', 'w') as f:
    json.dump(val_data, f)
with open(file_path + 'maude_dataset/test.json', 'w') as f:
    json.dump(test_data, f)


print(len(train_data), len(val_data), len(test_data))

2876 359 360

In [ ]:
from datasets import load_dataset

dataset = load_dataset("json", data_files=file_path + "maude_dataset/train.json", split="train")
print(dataset)

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['anchor', 'positive', 'negative'],
    num_rows: 2876
})

### Test with pre-trained embedding model

In [ ]:
import faiss
import numpy as np
from huggingface_hub import login
from sentence_transformers.evaluation import TripletEvaluator
from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import DataLoader
import os
from datasets import load_dataset

login(token="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")
os.environ["WANDB_DISABLED"] = "true"

import torch
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(DEVICE)

cuda

In [ ]:
import logging
from sentence_transformers.evaluation import TripletEvaluator
from torch.utils.data import DataLoader
import torch
from sentence_transformers.losses import MultipleNegativesRankingLoss
# ALLMINI_NAME = "sentence-transformers/all-MiniLM-L6-v2"
# GIST_NAME = "avsolatorio/GIST-small-Embedding-v0"


train_dataset = load_dataset("json", data_files=file_path + "maude_dataset/train.json", split="train")
val_dataset = load_dataset("json", data_files=file_path + "maude_dataset/val.json", split="train")

# Load model
model = SentenceTransformer(GIST_NAME, device=DEVICE)

# # Prepare dataset
def prepare_dataset(dataset):
  train_examples = []
  for example in dataset:  # Assume dataset is loaded from JSON
      query = example["anchor"]
      pos_doc = f"{example['positive']['doc_id']} | " \
                f"{example['positive']['text']}"
      neg_doc = f"{example['negative']['doc_id']} | " \
                f"{example['negative']['text']}"
      train_examples.append(InputExample(texts=[query, pos_doc, neg_doc]))
  return train_examples


train_examples = prepare_dataset(train_dataset)
val_examples = prepare_dataset(val_dataset)

# # Create DataLoader
train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=16)
val_dataloader   = DataLoader(val_examples, shuffle=False, batch_size=16)

# Define loss (Triplet loss for query, positive, negative)
train_loss = losses.BatchHardTripletLoss(model)
val_evaluator = TripletEvaluator.from_input_examples(val_examples, name="val")
val_evaluator(model)

loss = MultipleNegativesRankingLoss(model)

## Contrative learning
from sentence_transformers import SentenceTransformerTrainingArguments, SentenceTransformerTrainer

training_args = SentenceTransformerTrainingArguments(
    output_dir="finetuned_gist_retriever",
    num_train_epochs=5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_ratio=0.1,
    # batch_sampler=BatchSamplers.NO_DUPLICATES,
    logging_dir="logs",
    logging_steps=100,
    eval_strategy="steps",
    eval_steps=100,
)

trainer = SentenceTransformerTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    loss=loss,
    evaluator=val_evaluator,
)

trainer.train()

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

TrainOutput(global_step=900, training_loss=0.09116013911035326, metrics={'train_runtime': 162.0602, 'train_samples_per_second': 88.732, 'train_steps_per_second': 5.553, 'total_flos': 0.0, 'train_loss': 0.09116013911035326, 'epoch': 5.0})

In [ ]:
test_dataset = load_dataset("json", data_files=file_path + "maude_dataset/test.json", split="train")
positives = [str(p["doc_id"]) for p in test_dataset["positive"]]
negatives = [str(n["doc_id"]) for n in test_dataset["negative"]]
anchors = [str(x) for x in test_dataset["anchor"]]
test_evaluater = TripletEvaluator(
    anchors = anchors,
    positives = positives,
    negatives = negatives
)
test_evaluater(model)

{'cosine_accuracy': 1.0}

### Evaluating the final result for fine-tuned retriever/embedding model

In [ ]:
### Load fine-tuned model
embeddings = SentenceTransformer(file_path + "finetuned_gist_retriever")
embedding_function = MyEmbeddingFunction(embeddings)

### Build the vector store with fine-tuned model
client = chromadb.PersistentClient(path=CHROMA_PATH)
existing_collections = [c.name for c in client.list_collections()]
COLLECTION_FINETUNED_PATH = "langchain-finetuned-GIST"

if COLLECTION_FINETUNED_PATH in existing_collections:
    print(f"Collection '{COLLECTION_FINETUNED_PATH}' already exists. Loading it.")
    collection = client.get_collection(COLLECTION_FINETUNED_PATH)
else:
    print(f"Collection '{COLLECTION_FINETUNED_PATH}' not found. Creating new one...")
    # client.delete_collection(COLLECTION_FINETUNED_PATH)
    creating_chromadb(alldata, embeddings, collection_path = COLLECTION_FINETUNED_PATH)

vectorstore = Chroma(
    collection_name=COLLECTION_FINETUNED_PATH,
    embedding_function=embedding_function,
    persist_directory=CHROMA_PATH
)
st.session_state.retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 1}
)
st.success("Done")

2025-07-28 12:59:38.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-28 12:59:38.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-28 12:59:38.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-28 12:59:38.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-28 12:59:38.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Collection 'langchain-finetuned-GIST' already exists. Loading it.

DeltaGenerator()

In [ ]:
retriever = vectorstore.as_retriever(search_type="similarity", search_kwargs={"k": 1})

### Load the test.json
from datasets import load_dataset
dataset = load_dataset("json", data_files=file_path + "maude_dataset/test.json", split="train")
data = pd.DataFrame(columns=["anchor", "expected_MDR_REPORT_KEY", "actual_MDR_REPORT_KEY", "correctness"])

for i in dataset:
    retrieved_docs = retriever.get_relevant_documents(i["anchor"])
    top1_doc = retrieved_docs[0]

    data = pd.concat([data, pd.DataFrame([{
        "anchor": i["anchor"],
        "expected_MDR_REPORT_KEY": i["positive"]["doc_id"],
        "actual_MDR_REPORT_KEY": top1_doc.metadata["MDR_REPORT_KEY"],
        "correctness": str(i["positive"]["doc_id"]).strip() == str(top1_doc.metadata["MDR_REPORT_KEY"]).strip()
    }])], ignore_index=True)


data["correctness"].value_counts()

correctness
False    359
True       1
Name: count, dtype: int64

### Conclusion of fine-tuning embedding model
I was wrong. It is not ideal to train the embedding model in this way because anchor/positive/negative is usually used to train the model to favor one answer, not for retrieving.

For example:
anchor: What causes chest pain?,
positive: Why do I feel pain in chest?
negative: How to treat foot fungus?
The idea is to embed semantically similar questions (anchor & positive) closer together, and push dissimilar ones (negatives) apart in vector space. But, this is not applied to the retriever

### Evaluate the performance of LLM

In [ ]:
! pip install evaluate rouge_score

In [32]:
### 2. Evaluating Base LLaMA-2 on MAUDE Dataset
import numpy as np
from sentence_transformers import SentenceTransformer
import evaluate
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from langchain.chains import RetrievalQA
from langchain.vectorstores import Milvus
from sklearn.metrics.pairwise import cosine_similarity
import json

from huggingface_hub import login
login(token="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")

# Load base Mistral-7B
# model_id = "mistralai/Mistral-7B-Instruct-v0.3"
model_id = "meta-llama/Llama-3.2-1B"
tokenizer = AutoTokenizer.from_pretrained(model_id)
llm = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype="auto", device_map={"": 0})

pipe = pipeline("text-generation", model=llm, tokenizer=tokenizer, max_new_tokens=200)

from langchain.llms import HuggingFacePipeline
llm = HuggingFacePipeline(pipeline=pipe)

import os
from langchain_chroma import Chroma
import chromadb
from sentence_transformers import SentenceTransformer

from langchain_core.retrievers import BaseRetriever
from typing import Callable
import re
from langchain_chroma import Chroma
from langchain_core.documents import Document

CHROMA_PATH = file_path + "chroma"
COLLECTION_PRETRAINED_GISTPATH = "langchain-pretrained-GIST"

class CustomRetriever(BaseRetriever):
    vectorstore: Chroma
    filter_func: Callable  = None

    class Config:
        arbitrary_types_allowed = True

    def _get_relevant_documents(self, query: str) -> list[Document]:
        # Optional: Extract a doc_id from query
        client = chromadb.PersistentClient(path=CHROMA_PATH)
        collection = client.get_collection(name=COLLECTION_PRETRAINED_GISTPATH)

        doc_id = None
        match = re.search(r"\b\d{8}\b", query)
        if match:
            doc_id = match.group()

        # Filter metadata if applicable
        search_kwargs = {"k": 1}
        if doc_id:
            ### Metadata filtering
            results = collection.get(
                where={"MDR_REPORT_KEY": doc_id},
                # where={"$and": [
                #     {"MDR_REPORT_KEY": doc_id},
                #     # {"PATIENT_SEX": "Male"},
                #     # {"YEAR": "2022"}
                # ]},
                include=["documents", "metadatas"]
            )

            docs = [
                Document(page_content=doc, metadata=metadata)
                for doc, metadata in zip(results["documents"], results["metadatas"])
            ]
            print(f"doc_id {doc_id} found")
            return docs

        retriever = self.vectorstore.as_retriever(
            search_type="similarity",
            search_kwargs=search_kwargs
        )
        return retriever.get_relevant_documents(query)

class MyEmbeddingFunction:
    def __init__(self, embedding_model):
        self.embedding_model = embedding_model

    def __call__(self, input):
        # Chroma may call this if it supports function-style
        return self.embedding_model.encode(input, convert_to_tensor=False).tolist()

    def embed_query(self, input):
        return self.embedding_model.encode(input, convert_to_tensor=False).tolist()

    def embed_documents(self, input):
        return self.embedding_model.encode(input, convert_to_tensor=False).tolist()

tokenizer_config.json:   0%|          | 0.00/50.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/843 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

RuntimeError: Cannot access accelerator device when none is available.

In [ ]:
# Set up retriever
# Load MAUDE test dataset
with open(file_path + 'maude_dataset/test.json', 'r') as f:
    test_data = json.load(f)
    # test_data = test_data[:10]

embeddings = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
embedding_function = MyEmbeddingFunction(embeddings)
vectorstore = Chroma(
    collection_name=COLLECTION_PATH,
    embedding_function=embedding_function,
    persist_directory=CHROMA_PATH
)

# RAG pipeline
custom_retriever = CustomRetriever(vectorstore=vectorstore)
rag_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=custom_retriever
)

# Generate responses
test_queries = [item['anchor'] for item in test_data]
base_answers = [rag_chain.run(q) for q in test_queries]
### this should be the direct answer: eg: Male/2024/occlusion
def find_groundtruth(query, raw_string):
  raw_string = raw_string[0].page_content
  document = dict(line.split(":", 1) for line in raw_string.splitlines())
  query = str(query).lower()
  if "patient gender" in str(query):
      return document["PATIENT_SEX"]
  elif "adverse events" in str(query):
      return document["ADVERSE_EVENTS"]
  if "year" in str(query):
      return int(document["YEAR"])

ground_truths = [find_groundtruth(item["anchor"], item["positive"]["text"]) for item in test_data]
contexts = [item['positive']["text"] for item in test_data]
# Evaluate
eval_data = Dataset.from_dict({
    "question": test_queries,
    "answer": base_answers,
    "contexts": contexts,
    "ground_truths": ground_truths
})
print("eval_data", eval_data)

In [ ]:
import pandas as pd
eval_data = pd.read_csv(file_path + "eval_data_pretrained_llama_results.csv")
eval_data["answer"] = eval_data["answer"].astype(str)
eval_data["ground_truths"] = eval_data["ground_truths"].astype(str)
eval_data = Dataset.from_pandas(eval_data)
eval_data

Dataset({
    features: ['question', 'answer', 'contexts', 'ground_truths'],
    num_rows: 360
})

In [ ]:
import evaluate

predictions = eval_data["answer"]
references = eval_data["ground_truths"]

exact_match = evaluate.load("exact_match")
em_result = exact_match.compute(predictions=predictions, references=references)
# bleu = evaluate.load("bleu")
# bleu_result = bleu.compute(predictions=predictions, references=[[ref] for ref in references])
rouge = evaluate.load("rouge")
rouge_result = rouge.compute(predictions=predictions, references=references)



# f1 = evaluate.load("f1")

#

print("Exact Match:", em_result)
print("ROUGE:", rouge_result)

Exact Match: {'exact_match': np.float64(0.0)}
ROUGE: {'rouge1': np.float64(0.020747746094674197), 'rouge2': np.float64(0.0), 'rougeL': np.float64(0.02076644270984961), 'rougeLsum': np.float64(0.020706230972101874)}

In [ ]:
df = eval_data.to_pandas()

# Save to CSV
df.to_csv(file_path + "eval_data_pretrained_llama_results.csv", index=False)